version: '3.3'
services:
  employees.application:
    image: hotel.application
    build:
      context: .
      dockerfile: HotelWebApplication/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - database
    networks:
      - backend
    restart: always
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'hotel'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'hotel'
    networks:
      - backend
    ports:
      - "5431:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  database-pg:
